### PR TITLE
2016.11 compat

### PR DESCRIPTION
**Pull request by cinterloper**
this appears to work just fine for 2016.11, we dont actually want to use black/white lists yet

### CODE REVIEW

**Comment by hspak** [comment]
I believe they're supposed to be arrays not dicts, but I don't know if it matters.
https://github.com/saltstack/salt/commit/17b03e9d8b2109fb78c9cfdf5ff65aa988dab130

There should be a way to pull the Salt version from their library so we can have this support both versions.

**Comment by cinterloper** [comment]
Should be ready, what do you think @hspak ?

**Comment by hspak** [comment]
The blacklist,whitelist arguments aren't kwargs here: https://github.com/saltstack/salt/commit/17b03e9d8b2109fb78c9cfdf5ff65aa988dab130#diff-ff0281eb3cb6633302f7d77137e01028R30

Does it still work for 2016.11?

**Comment by cinterloper** [comment]
Yes, I have tested on use1

**Comment by hspak** [comment]
Cool, looks good then! 👍

**Pull request merged**
